### ISSUE TITLE
I don't understand how to use your package and AppCues 

### ISSUE THREAD

**Issue by yelkamel** [appcues/appcues-flutter-plugin#33]
As the CTO of Evolum app, we need to have an onboarding process with no code and update without publishing to the App Store.

It's a flutter app. I check the documentation and the example source code and I see only method to track Sceen or Event... 

I don't understand how AppClues Flutter package can help us ? 

Why we don't have method like show screen with and ID for example ? 

Regards,
Youcef EL KAMEL

**Comment by yelkamel** [comment]
Oh okay so when I will log screen event how AppCues will understand that it's will have to show a pop ? The event name String (with white space) will be the key  ? :o 

Appcues.initialize('APPCUES_ACCOUNT_ID', 'APPCUES_APPLICATION_ID');

I don't find "APPCUES_APPLICATION_ID" anywhere in appcues studio...
I tried to do that: 
Log into Appcues Studio → Settings → Apps & Installation → Add App → Enter your App's name and select the type of app (e.g. Android, iOS or cross platform framework). → Click Save.  A unique App ID is generated and displayed.
 
But when I go to setting I have only Installation in the menu... 

I'm used to try a lot of service but I don't know why I don't understand AppCues :( 
Make it simple please.

and we don't have flutter here:

<img width="1110" alt="CleanShot 2023-03-20 at 15 22 38@2x" src="https://user-images.githubusercontent.com/10924422/226369227-f625eb66-7c0e-46d8-916d-5982f21aaa4e.png">

Youcef

I'm only giving feedback and thanks for that product who look great, I want my nocode builder to be autonomous in the onboarding screen process of my app Evolum (4,9/5 with +30k review).

**Comment by mmaatttt** [comment]
Hi Youcef,

We really appreciate the feedback, so keep it coming! And we definitely understand the quality bar you have for your app. That's why our mobile SDKs are fully open source so that you can inspect all the code that will be included in your app.

> Oh okay so when I will log screen event how AppCues will understand that it's will have to show a pop ? The event name String (with white space) will be the key ? :o

Yes, Appcues takes the current screen name and all the other targeting rules you've defined to decide when to show a flow. The screen/event name may have whitespace, but doesn't have to. It's up to you, so if you'd rather do something like `user-profile`, that works perfectly fine as well.

Regarding the `APPCUES_APPLICATION_ID`, my apologies for the confusion. The mobile settings are currently enabled on a per-customer basis to avoid confusing our existing customer base. We've enabled the mobile settings for your account, so now if you go to the Settings, you'll have the option to add your Flutter app ([direct link](https://studio.appcues.com/settings/installation)) and get your Application ID value.

I will also note that as part of your trial of Appcues, you will be able to preview flows created in the Appcues Mobile Builder in your app, but you won't be able to publish the flows you create and target them to the screens you define with `Appcues.screen('<screen-name>')`. If you're interested in publishing to test the full end-to-end capabilities of Appcues in your app, your Appcues sales contact (they'll be reaching out shortly) can help you with that.

Let me know if you have any more questions!

Matt
