### ISSUE TITLE
Not running in Android with error: Error while dexing.

### ISSUE THREAD

**Issue by luismalodgify** [appcues/appcues-flutter-plugin#67]
When trying to run a new Flutter project (or any other) on Android the following error occurs. The configuration is set as the Flutter docs, check also below.
Thanks

Error:
<img width="944" alt="image" src="https://github.com/appcues/appcues-flutter-plugin/assets/99809304/12136196-95ab-45db-bddf-43865baeba47">

Flutter doctor:
<img width="693" alt="image" src="https://github.com/appcues/appcues-flutter-plugin/assets/99809304/df492880-d8ff-41ba-b84d-3fe0db3995ef">

android/app/build.gradle:

<img width="996" alt="image" src="https://github.com/appcues/appcues-flutter-plugin/assets/99809304/722ebf87-9a93-42c6-a733-076378164352">

project pubspec.yaml:

<img width="649" alt="image" src="https://github.com/appcues/appcues-flutter-plugin/assets/99809304/c8258ccb-2f28-4e08-971a-36998a5f9a74">

**Comment by andretortolano** [comment]
Thanks @luismalodgify for reaching out with this, I'm able to reproduce, looking into it and I will let you know when we have a  fix

**Comment by andretortolano** [comment]
Still need to look into a more permanent fix, but it seems like there is an work around for this issue. I tested and it seems to work.

on settings.gradle

```
pluginManagement {
   ...

    buildscript {
        repositories {
            mavenCentral()
            maven {
                url = uri("https://storage.googleapis.com/r8-releases/raw")
            }
        }
        dependencies {
            classpath("com.android.tools:r8:8.2.26")
        }
    }
}
```

[link](https://issuetracker.google.com/issues/227160052#comment37) for reference.

let me know if that helps on your end

**Comment by luismalodgify** [comment]
Thanks for the quick response @andretortolano , yes this works for me to

**Comment by iujames** [comment]
Hi @luismalodgify , noting one other finding here. This may be related to the version of the Android Gradle Plugin (AGP) in use in the project. When creating a new project, using Flutter 3.16.9 (latest), I noticed this in the android project settings.gradle file

```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
}
```

I was able to reproduce the same issue noted in this thread when adding the Appcues plugin - "Error while dexing".

If I update the settings.gradle file to use
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.4.2" apply false
}
```

The issue was resolved, and my app could build and run as expected. I believe AGP 7.4.2+ is required for the Appcues Android plugin. The example app structure in this repo is a little differently, but it also applies AGP 7.4.2 in this location https://github.com/appcues/appcues-flutter-plugin/blob/main/example/android/build.gradle#L9.

This may be another option to evaluate as an alternative to specifying the `r8` dependency. If you are using an older AGP version, updating to something more recent may help avoid other future issues as well. Thanks!
